[2025-03-03 09:01:24,479] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 09:01:42,903] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/hello/
Traceback (most recent call last):
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py", line 15, in hello
    print("GET:"+params)
TypeError: can only concatenate str (not "dict") to str
[2025-03-03 09:01:42,916] [basehttp.py:212] [basehttp:log_message] [ERROR]- "GET /api/hello/ HTTP/1.1" 500 68732
[2025-03-03 09:01:54,227] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/hello/
Traceback (most recent call last):
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py", line 15, in hello
    print("GET:"+params)
TypeError: can only concatenate str (not "dict") to str
[2025-03-03 09:01:54,237] [basehttp.py:212] [basehttp:log_message] [ERROR]- "GET /api/hello/ HTTP/1.1" 500 68732
[2025-03-03 09:02:06,101] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py changed, reloading.
[2025-03-03 09:02:10,033] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 09:02:29,583] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 09:02:34,052] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/hello?abc=1 HTTP/1.1" 301 0
[2025-03-03 09:02:44,714] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/hello/
Traceback (most recent call last):
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py", line 15, in hello
    print("GET:"+params)
TypeError: can only concatenate str (not "dict") to str
[2025-03-03 09:02:44,729] [basehttp.py:212] [basehttp:log_message] [ERROR]- "GET /api/hello/?abc=1 HTTP/1.1" 500 71701
[2025-03-03 09:02:44,947] [log.py:241] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2025-03-03 09:02:44,949] [basehttp.py:212] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 2214
[2025-03-03 09:03:16,182] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py changed, reloading.
[2025-03-03 09:03:18,396] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 09:03:27,745] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/hello?abc=1 HTTP/1.1" 301 0
[2025-03-03 09:03:43,753] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 09:03:51,958] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/hello?abc=1 HTTP/1.1" 301 0
[2025-03-03 09:03:59,111] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/hello?abc=1 HTTP/1.1" 301 0
[2025-03-03 09:04:15,103] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py changed, reloading.
[2025-03-03 09:04:17,003] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 09:04:37,803] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 09:04:45,273] [log.py:241] [log:log_response] [WARNING]- Not Found: /api/hello/abc=1
[2025-03-03 09:04:45,276] [basehttp.py:212] [basehttp:log_message] [WARNING]- "GET /api/hello/abc=1 HTTP/1.1" 404 2281
[2025-03-03 09:05:00,215] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py changed, reloading.
[2025-03-03 09:05:08,907] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 09:05:19,120] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/hello?abc=1 HTTP/1.1" 301 0
[2025-03-03 09:05:22,247] [log.py:241] [log:log_response] [WARNING]- Not Found: /api/hello/abc=1
[2025-03-03 09:05:22,249] [basehttp.py:212] [basehttp:log_message] [WARNING]- "GET /api/hello/abc=1 HTTP/1.1" 404 2281
[2025-03-03 09:06:42,390] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py changed, reloading.
[2025-03-03 09:06:44,458] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 09:07:25,281] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 09:07:34,329] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/hello/
Traceback (most recent call last):
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py", line 11, in hello
    print("user_agent:"+json.dumps(params))
UnboundLocalError: local variable 'params' referenced before assignment
[2025-03-03 09:07:34,343] [basehttp.py:212] [basehttp:log_message] [ERROR]- "GET /api/hello/?name=Owen HTTP/1.1" 500 71543
[2025-03-03 09:07:53,497] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py changed, reloading.
[2025-03-03 09:07:55,804] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 09:08:12,684] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/hello/
Traceback (most recent call last):
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py", line 16, in hello
    print("GET:"+params)
TypeError: can only concatenate str (not "dict") to str
[2025-03-03 09:08:12,709] [basehttp.py:212] [basehttp:log_message] [ERROR]- "GET /api/hello/?name=Owen HTTP/1.1" 500 71882
[2025-03-03 09:09:10,976] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 09:09:28,542] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/hello/?name=Owen HTTP/1.1" 200 28
[2025-03-03 09:09:49,222] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py changed, reloading.
[2025-03-03 09:09:51,154] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 09:10:01,911] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py changed, reloading.
[2025-03-03 09:10:12,708] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 09:10:38,765] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/hello/?name=Owen HTTP/1.1" 200 28
[2025-03-03 09:10:50,279] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py changed, reloading.
[2025-03-03 09:10:52,267] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 09:11:51,164] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/urls.py changed, reloading.
[2025-03-03 09:11:55,086] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 09:12:11,980] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/urls.py changed, reloading.
[2025-03-03 09:43:23,298] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 09:43:52,320] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/hello HTTP/1.1" 200 14
[2025-03-03 09:44:01,946] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/hello?name=Owen HTTP/1.1" 200 28
[2025-03-03 09:58:26,267] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 10:51:55,033] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 10:54:30,580] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 10:57:29,874] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 10:59:55,357] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 11:01:36,938] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 11:01:53,470] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/hello?name=Owen HTTP/1.1" 200 28
[2025-03-03 11:01:53,605] [log.py:241] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2025-03-03 11:01:53,608] [basehttp.py:212] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 2214
[2025-03-03 11:02:09,464] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py changed, reloading.
[2025-03-03 11:07:12,919] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 11:07:29,722] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py changed, reloading.
[2025-03-03 11:07:39,928] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 11:08:00,028] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/libitem
Traceback (most recent call last):
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py", line 59, in libitem
    return JsonResponse(datas)
  File "/home/owen/.local/lib/python3.10/site-packages/django/http/response.py", line 724, in __init__
    raise TypeError(
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
[2025-03-03 11:08:00,041] [basehttp.py:212] [basehttp:log_message] [ERROR]- "GET /api/libitem?name=Owen HTTP/1.1" 500 91508
[2025-03-03 11:08:48,531] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py changed, reloading.
[2025-03-03 11:08:50,533] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 11:08:52,071] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py changed, reloading.
[2025-03-03 11:09:02,354] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 11:09:09,379] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/libitem
Traceback (most recent call last):
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py", line 68, in libitem
    return JsonResponse(response_data)
  File "/home/owen/.local/lib/python3.10/site-packages/django/http/response.py", line 731, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/usr/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/serializers/json.py", line 106, in default
    return super().default(o)
  File "/usr/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
[2025-03-03 11:09:09,383] [basehttp.py:212] [basehttp:log_message] [ERROR]- "GET /api/libitem?name=Owen HTTP/1.1" 500 140064
[2025-03-03 11:09:26,553] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/libitem
Traceback (most recent call last):
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py", line 68, in libitem
    return JsonResponse(response_data)
  File "/home/owen/.local/lib/python3.10/site-packages/django/http/response.py", line 731, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/usr/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/serializers/json.py", line 106, in default
    return super().default(o)
  File "/usr/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
[2025-03-03 11:09:26,561] [basehttp.py:212] [basehttp:log_message] [ERROR]- "GET /api/libitem?name=Owen HTTP/1.1" 500 140201
[2025-03-03 11:10:42,848] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py changed, reloading.
[2025-03-03 11:10:45,420] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 11:12:47,042] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/libitem
Traceback (most recent call last):
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py", line 67, in libitem
    return JsonResponse(response_data)
  File "/home/owen/.local/lib/python3.10/site-packages/django/http/response.py", line 731, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/usr/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/serializers/json.py", line 106, in default
    return super().default(o)
  File "/usr/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
[2025-03-03 11:12:47,049] [basehttp.py:212] [basehttp:log_message] [ERROR]- "GET /api/libitem?name=Owen HTTP/1.1" 500 140355
[2025-03-03 11:13:33,694] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/libitem
Traceback (most recent call last):
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py", line 67, in libitem
    return JsonResponse(response_data)
  File "/home/owen/.local/lib/python3.10/site-packages/django/http/response.py", line 731, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/usr/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/serializers/json.py", line 106, in default
    return super().default(o)
  File "/usr/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
[2025-03-03 11:13:33,696] [basehttp.py:212] [basehttp:log_message] [ERROR]- "GET /api/libitem?name=Owen HTTP/1.1" 500 140306
[2025-03-03 11:13:38,027] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/libitem
Traceback (most recent call last):
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py", line 67, in libitem
    return JsonResponse(response_data)
  File "/home/owen/.local/lib/python3.10/site-packages/django/http/response.py", line 731, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/usr/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/serializers/json.py", line 106, in default
    return super().default(o)
  File "/usr/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
[2025-03-03 11:13:38,029] [basehttp.py:212] [basehttp:log_message] [ERROR]- "GET /api/libitem?name=Owen HTTP/1.1" 500 140064
[2025-03-03 11:13:53,276] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 11:14:06,614] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/libitem
Traceback (most recent call last):
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py", line 67, in libitem
    return JsonResponse(response_data)
  File "/home/owen/.local/lib/python3.10/site-packages/django/http/response.py", line 731, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/usr/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/serializers/json.py", line 106, in default
    return super().default(o)
  File "/usr/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
[2025-03-03 11:14:06,617] [basehttp.py:212] [basehttp:log_message] [ERROR]- "GET /api/libitem?name=Owen HTTP/1.1" 500 140064
[2025-03-03 11:14:56,654] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py changed, reloading.
[2025-03-03 11:14:58,572] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 11:15:06,234] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py changed, reloading.
[2025-03-03 11:15:10,139] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 11:15:33,265] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py changed, reloading.
[2025-03-03 11:15:43,243] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 11:15:58,335] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/libitem?name=Owen HTTP/1.1" 200 8848
[2025-03-03 11:18:33,200] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 11:18:42,556] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/libitem?name=Owen HTTP/1.1" 200 8848
[2025-03-03 11:18:50,222] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py changed, reloading.
[2025-03-03 11:18:52,039] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 11:18:55,671] [log.py:241] [log:log_response] [WARNING]- Not Found: /api/libitem
[2025-03-03 11:18:55,674] [basehttp.py:212] [basehttp:log_message] [WARNING]- "GET /api/libitem?name=Owen HTTP/1.1" 404 8848
[2025-03-03 11:21:10,011] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 11:21:18,960] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/libitem?name=Owen HTTP/1.1" 200 8848
[2025-03-03 11:23:44,587] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 11:23:51,042] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/libitem?name=Owen HTTP/1.1" 200 8848
[2025-03-03 11:24:16,425] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 11:24:47,069] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/libitem?name=Owen HTTP/1.1" 200 8848
[2025-03-03 11:24:47,269] [log.py:241] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2025-03-03 11:24:47,271] [basehttp.py:212] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 2214
[2025-03-03 11:24:54,440] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py changed, reloading.
[2025-03-03 11:24:56,604] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 11:25:18,738] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py changed, reloading.
[2025-03-03 11:25:22,626] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 11:26:46,212] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py changed, reloading.
[2025-03-03 11:26:49,801] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 11:27:11,862] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py changed, reloading.
[2025-03-03 11:27:16,363] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 11:27:33,113] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py changed, reloading.
[2025-03-03 11:27:35,047] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 11:27:39,046] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/libitem
Traceback (most recent call last):
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py", line 89, in libitem
    data=convert_model_to_dict(item)
  File "/home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py", line 45, in convert_model_to_dict
    isdeleted_value = value.isdeleted
AttributeError: 'bytes' object has no attribute 'isdeleted'
[2025-03-03 11:27:39,049] [basehttp.py:212] [basehttp:log_message] [ERROR]- "GET /api/libitem?name=Owen HTTP/1.1" 500 78708
[2025-03-03 11:27:56,916] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/libitem
Traceback (most recent call last):
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py", line 89, in libitem
    data=convert_model_to_dict(item)
  File "/home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py", line 45, in convert_model_to_dict
    isdeleted_value = value.isdeleted
AttributeError: 'bytes' object has no attribute 'isdeleted'
[2025-03-03 11:27:56,932] [basehttp.py:212] [basehttp:log_message] [ERROR]- "GET /api/libitem?name=Owen HTTP/1.1" 500 79055
[2025-03-03 11:28:15,666] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py changed, reloading.
[2025-03-03 11:28:17,561] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 11:28:45,616] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/libitem
Traceback (most recent call last):
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py", line 84, in libitem
    data=convert_model_to_dict(item)
  File "/home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py", line 40, in convert_model_to_dict
    isdeleted_value = value.isdeleted
AttributeError: 'bytes' object has no attribute 'isdeleted'
[2025-03-03 11:28:45,632] [basehttp.py:212] [basehttp:log_message] [ERROR]- "GET /api/libitem?name=Owen HTTP/1.1" 500 78487
[2025-03-03 11:29:23,209] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py changed, reloading.
[2025-03-03 11:29:25,413] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 11:29:29,036] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py changed, reloading.
[2025-03-03 11:29:33,131] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 11:29:34,640] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py changed, reloading.
[2025-03-03 11:29:38,772] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 11:29:56,339] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/libitem?name=Owen HTTP/1.1" 200 8818
[2025-03-03 11:31:41,380] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py changed, reloading.
[2025-03-03 11:31:45,061] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 11:32:32,288] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 11:32:43,299] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/libitem?name=Owen HTTP/1.1" 200 8818
[2025-03-03 11:36:29,159] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 11:36:38,951] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/libitem?name=Owen HTTP/1.1" 200 8818
[2025-03-03 12:29:15,315] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 12:31:35,983] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 12:31:46,130] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/libitem?name=Owen HTTP/1.1" 200 5228
[2025-03-03 12:32:06,660] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 302 0
[2025-03-03 12:32:06,724] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4195
[2025-03-03 12:32:11,649] [basehttp.py:212] [basehttp:log_message] [INFO]- "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
[2025-03-03 12:32:11,788] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 6224
[2025-03-03 12:32:11,912] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /static/admin/css/dashboard.css HTTP/1.1" 200 441
[2025-03-03 12:32:11,914] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
[2025-03-03 12:32:11,919] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
[2025-03-03 12:32:18,083] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /admin/authtoken/tokenproxy/add/ HTTP/1.1" 200 9237
[2025-03-03 12:32:18,117] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /static/admin/css/forms.css HTTP/1.1" 200 9090
[2025-03-03 12:32:18,131] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 292458
[2025-03-03 12:32:18,150] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /static/admin/js/jquery.init.js HTTP/1.1" 200 347
[2025-03-03 12:32:18,192] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /static/admin/js/actions.js HTTP/1.1" 200 7872
[2025-03-03 12:32:18,197] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 8943
[2025-03-03 12:32:18,202] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1531
[2025-03-03 12:32:18,205] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /static/admin/js/urlify.js HTTP/1.1" 200 7887
[2025-03-03 12:32:18,220] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /static/admin/js/core.js HTTP/1.1" 200 5682
[2025-03-03 12:32:18,244] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /static/admin/css/widgets.css HTTP/1.1" 200 11921
[2025-03-03 12:32:18,265] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 586
[2025-03-03 12:32:18,268] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /static/admin/img/icon-viewlink.svg HTTP/1.1" 200 581
[2025-03-03 12:32:18,270] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 232381
[2025-03-03 12:32:18,334] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8560
[2025-03-03 12:32:18,346] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /static/admin/js/change_form.js HTTP/1.1" 200 606
[2025-03-03 12:32:23,732] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /admin/authtoken/tokenproxy/add/
Traceback (most recent call last):
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/home/owen/.local/lib/python3.10/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/owen/.local/lib/python3.10/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/owen/.local/lib/python3.10/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.ProgrammingError: (1146, "Table 'djangodb.authtoken_token' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/owen/.local/lib/python3.10/site-packages/django/contrib/admin/options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/owen/.local/lib/python3.10/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/owen/.local/lib/python3.10/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/owen/.local/lib/python3.10/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/home/owen/.local/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1886, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/home/owen/.local/lib/python3.10/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/owen/.local/lib/python3.10/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/owen/.local/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1747, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/home/owen/.local/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1792, in _changeform_view
    form_validated = form.is_valid()
  File "/home/owen/.local/lib/python3.10/site-packages/django/forms/forms.py", line 201, in is_valid
    return self.is_bound and not self.errors
  File "/home/owen/.local/lib/python3.10/site-packages/django/forms/forms.py", line 196, in errors
    self.full_clean()
  File "/home/owen/.local/lib/python3.10/site-packages/django/forms/forms.py", line 435, in full_clean
    self._post_clean()
  File "/home/owen/.local/lib/python3.10/site-packages/django/forms/models.py", line 492, in _post_clean
    self.validate_unique()
  File "/home/owen/.local/lib/python3.10/site-packages/django/forms/models.py", line 501, in validate_unique
    self.instance.validate_unique(exclude=exclude)
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/models/base.py", line 1229, in validate_unique
    errors = self._perform_unique_checks(unique_checks)
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/models/base.py", line 1339, in _perform_unique_checks
    if qs.exists():
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/models/query.py", line 1241, in exists
    return self.query.has_results(using=self.db)
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 598, in has_results
    return compiler.has_results()
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1530, in has_results
    return bool(self.execute_sql(SINGLE))
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/home/owen/.local/lib/python3.10/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/owen/.local/lib/python3.10/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/owen/.local/lib/python3.10/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'djangodb.authtoken_token' doesn't exist")
[2025-03-03 12:32:23,749] [basehttp.py:212] [basehttp:log_message] [ERROR]- "POST /admin/authtoken/tokenproxy/add/ HTTP/1.1" 500 223089
[2025-03-03 12:32:27,384] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /admin/authtoken/tokenproxy/add/ HTTP/1.1" 200 9237
[2025-03-03 12:32:28,976] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /admin/authtoken/tokenproxy/add/
Traceback (most recent call last):
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/home/owen/.local/lib/python3.10/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/owen/.local/lib/python3.10/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/owen/.local/lib/python3.10/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.ProgrammingError: (1146, "Table 'djangodb.authtoken_token' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/owen/.local/lib/python3.10/site-packages/django/contrib/admin/options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/owen/.local/lib/python3.10/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/owen/.local/lib/python3.10/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/owen/.local/lib/python3.10/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/home/owen/.local/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1886, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/home/owen/.local/lib/python3.10/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/owen/.local/lib/python3.10/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/owen/.local/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1747, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/home/owen/.local/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1792, in _changeform_view
    form_validated = form.is_valid()
  File "/home/owen/.local/lib/python3.10/site-packages/django/forms/forms.py", line 201, in is_valid
    return self.is_bound and not self.errors
  File "/home/owen/.local/lib/python3.10/site-packages/django/forms/forms.py", line 196, in errors
    self.full_clean()
  File "/home/owen/.local/lib/python3.10/site-packages/django/forms/forms.py", line 435, in full_clean
    self._post_clean()
  File "/home/owen/.local/lib/python3.10/site-packages/django/forms/models.py", line 492, in _post_clean
    self.validate_unique()
  File "/home/owen/.local/lib/python3.10/site-packages/django/forms/models.py", line 501, in validate_unique
    self.instance.validate_unique(exclude=exclude)
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/models/base.py", line 1229, in validate_unique
    errors = self._perform_unique_checks(unique_checks)
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/models/base.py", line 1339, in _perform_unique_checks
    if qs.exists():
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/models/query.py", line 1241, in exists
    return self.query.has_results(using=self.db)
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 598, in has_results
    return compiler.has_results()
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1530, in has_results
    return bool(self.execute_sql(SINGLE))
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/home/owen/.local/lib/python3.10/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/owen/.local/lib/python3.10/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/owen/.local/lib/python3.10/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'djangodb.authtoken_token' doesn't exist")
[2025-03-03 12:32:28,982] [basehttp.py:212] [basehttp:log_message] [ERROR]- "POST /admin/authtoken/tokenproxy/add/ HTTP/1.1" 500 223070
[2025-03-03 12:32:32,808] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /admin/authtoken/tokenproxy/add/ HTTP/1.1" 200 9237
[2025-03-03 12:32:34,495] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /admin/authtoken/tokenproxy/add/ HTTP/1.1" 200 9237
[2025-03-03 12:32:34,596] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8560
[2025-03-03 12:32:36,023] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /admin/auth/user/add/ HTTP/1.1" 200 10569
[2025-03-03 12:32:36,119] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8560
[2025-03-03 12:32:39,103] [basehttp.py:212] [basehttp:log_message] [INFO]- "POST /admin/auth/user/add/ HTTP/1.1" 200 10865
[2025-03-03 12:32:39,202] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8560
[2025-03-03 12:32:42,172] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /admin/authtoken/tokenproxy/
Traceback (most recent call last):
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/home/owen/.local/lib/python3.10/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/owen/.local/lib/python3.10/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/owen/.local/lib/python3.10/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.ProgrammingError: (1146, "Table 'djangodb.authtoken_token' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/owen/.local/lib/python3.10/site-packages/django/contrib/admin/options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/owen/.local/lib/python3.10/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/owen/.local/lib/python3.10/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/owen/.local/lib/python3.10/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/home/owen/.local/lib/python3.10/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/owen/.local/lib/python3.10/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/owen/.local/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1926, in changelist_view
    cl = self.get_changelist_instance(request)
  File "/home/owen/.local/lib/python3.10/site-packages/django/contrib/admin/options.py", line 836, in get_changelist_instance
    return ChangeList(
  File "/home/owen/.local/lib/python3.10/site-packages/django/contrib/admin/views/main.py", line 123, in __init__
    self.get_results(request)
  File "/home/owen/.local/lib/python3.10/site-packages/django/contrib/admin/views/main.py", line 279, in get_results
    result_count = paginator.count
  File "/home/owen/.local/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/paginator.py", line 93, in count
    return c()
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/models/query.py", line 608, in count
    return self.query.get_count(using=self.db)
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 568, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 554, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/home/owen/.local/lib/python3.10/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/owen/.local/lib/python3.10/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/owen/.local/lib/python3.10/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'djangodb.authtoken_token' doesn't exist")
[2025-03-03 12:32:42,178] [basehttp.py:212] [basehttp:log_message] [ERROR]- "GET /admin/authtoken/tokenproxy/ HTTP/1.1" 500 208364
[2025-03-03 12:37:10,913] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 12:38:48,307] [log.py:241] [log:log_response] [WARNING]- Not Found: /api/token/
[2025-03-03 12:38:48,309] [basehttp.py:212] [basehttp:log_message] [WARNING]- "POST /api/token/ HTTP/1.1" 404 2988
[2025-03-03 12:39:16,883] [log.py:241] [log:log_response] [WARNING]- Not Found: /api/protected/
[2025-03-03 12:39:16,884] [basehttp.py:212] [basehttp:log_message] [WARNING]- "GET /api/protected/ HTTP/1.1" 404 2999
[2025-03-03 12:39:26,599] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views_list/token_view.py changed, reloading.
[2025-03-03 12:39:30,702] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 12:39:36,046] [log.py:241] [log:log_response] [WARNING]- Not Found: /api/protected/
[2025-03-03 12:39:36,050] [basehttp.py:212] [basehttp:log_message] [WARNING]- "GET /api/protected/ HTTP/1.1" 404 2999
[2025-03-03 12:39:43,755] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views_list/token_view.py changed, reloading.
[2025-03-03 12:39:53,992] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 12:39:58,853] [log.py:241] [log:log_response] [WARNING]- Not Found: /api/protected/
[2025-03-03 12:39:58,855] [basehttp.py:212] [basehttp:log_message] [WARNING]- "GET /api/protected/ HTTP/1.1" 404 2999
[2025-03-03 12:40:25,708] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views_list/token_view.py changed, reloading.
[2025-03-03 12:42:21,457] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 12:42:26,701] [log.py:241] [log:log_response] [WARNING]- Not Found: /api/token/
[2025-03-03 12:42:26,705] [basehttp.py:212] [basehttp:log_message] [WARNING]- "POST /api/token/ HTTP/1.1" 404 2800
[2025-03-03 12:42:59,976] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 12:43:16,415] [log.py:241] [log:log_response] [WARNING]- Not Found: /api/admin
[2025-03-03 12:43:16,418] [basehttp.py:212] [basehttp:log_message] [WARNING]- "GET /api/admin HTTP/1.1" 404 2796
[2025-03-03 12:43:20,846] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 6224
[2025-03-03 12:43:23,142] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /admin/authtoken/tokenproxy/add/ HTTP/1.1" 200 9237
[2025-03-03 12:43:23,241] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8560
[2025-03-03 12:43:26,229] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /admin/authtoken/tokenproxy/add/
Traceback (most recent call last):
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/home/owen/.local/lib/python3.10/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/owen/.local/lib/python3.10/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/owen/.local/lib/python3.10/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.ProgrammingError: (1146, "Table 'djangodb.authtoken_token' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/owen/.local/lib/python3.10/site-packages/django/contrib/admin/options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/owen/.local/lib/python3.10/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/owen/.local/lib/python3.10/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/owen/.local/lib/python3.10/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/home/owen/.local/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1886, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/home/owen/.local/lib/python3.10/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/owen/.local/lib/python3.10/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/owen/.local/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1747, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/home/owen/.local/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1792, in _changeform_view
    form_validated = form.is_valid()
  File "/home/owen/.local/lib/python3.10/site-packages/django/forms/forms.py", line 201, in is_valid
    return self.is_bound and not self.errors
  File "/home/owen/.local/lib/python3.10/site-packages/django/forms/forms.py", line 196, in errors
    self.full_clean()
  File "/home/owen/.local/lib/python3.10/site-packages/django/forms/forms.py", line 435, in full_clean
    self._post_clean()
  File "/home/owen/.local/lib/python3.10/site-packages/django/forms/models.py", line 492, in _post_clean
    self.validate_unique()
  File "/home/owen/.local/lib/python3.10/site-packages/django/forms/models.py", line 501, in validate_unique
    self.instance.validate_unique(exclude=exclude)
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/models/base.py", line 1229, in validate_unique
    errors = self._perform_unique_checks(unique_checks)
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/models/base.py", line 1339, in _perform_unique_checks
    if qs.exists():
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/models/query.py", line 1241, in exists
    return self.query.has_results(using=self.db)
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 598, in has_results
    return compiler.has_results()
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1530, in has_results
    return bool(self.execute_sql(SINGLE))
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/home/owen/.local/lib/python3.10/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/owen/.local/lib/python3.10/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/owen/.local/lib/python3.10/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'djangodb.authtoken_token' doesn't exist")
[2025-03-03 12:43:26,242] [basehttp.py:212] [basehttp:log_message] [ERROR]- "POST /admin/authtoken/tokenproxy/add/ HTTP/1.1" 500 222926
[2025-03-03 12:44:52,529] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 12:45:40,594] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/hello?name=Owen HTTP/1.1" 200 28
[2025-03-03 12:45:46,107] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/libitem?name=Owen HTTP/1.1" 200 5228
[2025-03-03 12:45:48,850] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/libitem?name=Owen HTTP/1.1" 200 5228
[2025-03-03 12:45:51,111] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/libitem?format=json&name=Owen HTTP/1.1" 200 109
[2025-03-03 12:51:16,681] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 12:51:24,279] [basehttp.py:212] [basehttp:log_message] [INFO]- "POST /api/token/ HTTP/1.1" 200 149
[2025-03-03 12:51:37,485] [basehttp.py:212] [basehttp:log_message] [INFO]- "POST /api/token/ HTTP/1.1" 200 149
[2025-03-03 12:52:01,552] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 12:52:10,264] [basehttp.py:212] [basehttp:log_message] [INFO]- "POST /api/token/ HTTP/1.1" 200 514
[2025-03-03 12:52:21,312] [basehttp.py:212] [basehttp:log_message] [INFO]- "POST /api/token/refresh/ HTTP/1.1" 200 272
[2025-03-03 12:52:24,479] [basehttp.py:212] [basehttp:log_message] [INFO]- "POST /api/token/refresh/ HTTP/1.1" 200 272
[2025-03-03 12:53:29,969] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 12:53:35,762] [basehttp.py:212] [basehttp:log_message] [INFO]- "POST /api/token/ HTTP/1.1" 200 514
[2025-03-03 12:53:45,934] [basehttp.py:212] [basehttp:log_message] [INFO]- "POST /api/token/ HTTP/1.1" 200 514
[2025-03-03 12:53:58,231] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/libitem?name=Owen HTTP/1.1" 200 259
[2025-03-03 12:54:14,315] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views_list/libitem_view.py changed, reloading.
[2025-03-03 12:54:18,564] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 12:54:27,312] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/libitem?name=Owen HTTP/1.1" 200 259
[2025-03-03 12:54:36,660] [basehttp.py:212] [basehttp:log_message] [INFO]- "POST /api/token/ HTTP/1.1" 200 514
[2025-03-03 12:54:53,884] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/libitem?name=Owen HTTP/1.1" 200 259
[2025-03-03 12:55:07,157] [basehttp.py:212] [basehttp:log_message] [INFO]- "POST /api/token/ HTTP/1.1" 200 514
[2025-03-03 12:56:18,484] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/libitem?name=Owen HTTP/1.1" 200 8818
[2025-03-03 13:01:06,900] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 13:01:11,755] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/libitem?name=Owen HTTP/1.1" 301 0
[2025-03-03 13:01:11,854] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/libitem/?name=Owen HTTP/1.1" 200 5245
[2025-03-03 13:01:12,026] [log.py:241] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2025-03-03 13:01:12,028] [basehttp.py:212] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 2490
[2025-03-03 13:01:38,030] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 13:01:47,930] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/libitem/?name=Owen HTTP/1.1" 200 23745
[2025-03-03 13:04:34,439] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 13:05:06,873] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 13:06:06,370] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/djapps/settings.py changed, reloading.
[2025-03-03 13:06:08,349] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 13:08:47,633] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 13:10:52,709] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 13:10:58,916] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/libitem/?name=Owen HTTP/1.1" 200 23745
[2025-03-03 13:14:06,701] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 13:14:13,325] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/libitem/?name=Owen HTTP/1.1" 200 4920
[2025-03-03 13:14:13,472] [log.py:241] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2025-03-03 13:14:13,473] [basehttp.py:212] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 2490
[2025-03-03 13:14:19,885] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/libitem/?name=Owen HTTP/1.1" 200 4920
[2025-03-03 13:14:31,396] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/hello?name=Owen HTTP/1.1" 200 28
[2025-03-03 13:16:16,437] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 13:17:19,853] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 13:17:23,584] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/libitem/?name=Owen HTTP/1.1" 200 8818
[2025-03-03 13:31:30,234] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 13:31:35,026] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/libitems/ HTTP/1.1" 200 5025
[2025-03-03 13:31:35,146] [log.py:241] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2025-03-03 13:31:35,148] [basehttp.py:212] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 2490
[2025-03-03 13:32:07,194] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/libitems/ HTTP/1.1" 200 5025
[2025-03-03 13:33:19,503] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 13:33:42,522] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views_list/libitemviewset.py changed, reloading.
[2025-03-03 13:33:44,573] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 13:33:56,152] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/libitems/ HTTP/1.1" 200 8818
[2025-03-03 13:34:02,098] [log.py:241] [log:log_response] [WARNING]- Not Found: /api/libitems/123/
[2025-03-03 13:34:02,099] [basehttp.py:212] [basehttp:log_message] [WARNING]- "GET /api/libitems/123/ HTTP/1.1" 404 25
[2025-03-03 13:34:10,007] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/libitems/67b9cbf631ca40989b3b6f983be17d98/ HTTP/1.1" 200 853
[2025-03-03 13:34:17,421] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views_list/libitemviewset.py changed, reloading.
[2025-03-03 13:38:34,371] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 13:38:43,549] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views_list/libitemviewset.py changed, reloading.
[2025-03-03 13:38:45,650] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 13:39:07,683] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views_list/libitemviewset.py changed, reloading.
[2025-03-03 13:39:09,728] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 13:39:36,078] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 13:39:49,697] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views_list/libitemviewset.py changed, reloading.
[2025-03-03 13:39:51,641] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 13:39:54,857] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views_list/libitemviewset.py changed, reloading.
[2025-03-03 13:39:59,615] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 13:40:04,436] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/libitems/search-by-name?name=Owen HTTP/1.1" 301 0
[2025-03-03 13:40:04,716] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/libitems/search-by-name/
Traceback (most recent call last):
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/owen/.local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/owen/.local/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/owen/.local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/owen/.local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/owen/.local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/owen/.local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/owen/Github/PythonOwen/djangoapi/djapps/api/views_list/libitemviewset.py", line 51, in search_by_name
    results = Libitem.objects.filter(name__icontains=name)
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1546, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1577, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1427, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1237, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1725, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'name' into field. Choices are: author, barcode, bookbarcode, callno, catalogcode, createtype, creationtime, creatoruserid, deleteruserid, deletiontime, id, infoid, isbn, isdeleted, isenable, itemstate, itemtype, lastmodificationtime, lastmodifieruserid, locationid, locationname, origintype, pages, precallno, pressmarkid, pressmarkname, price, pubdate, publisher, pubno, remark, summary, tenantid, title
[2025-03-03 13:40:04,721] [basehttp.py:212] [basehttp:log_message] [ERROR]- "GET /api/libitems/search-by-name/?name=Owen HTTP/1.1" 500 144321
[2025-03-03 13:40:32,496] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/libitems/search-by-name/
Traceback (most recent call last):
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/owen/.local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/owen/.local/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/owen/.local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/owen/.local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/owen/.local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/owen/.local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/owen/Github/PythonOwen/djangoapi/djapps/api/views_list/libitemviewset.py", line 51, in search_by_name
    results = Libitem.objects.filter(name__icontains=name)
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1546, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1577, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1427, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1237, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1725, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'name' into field. Choices are: author, barcode, bookbarcode, callno, catalogcode, createtype, creationtime, creatoruserid, deleteruserid, deletiontime, id, infoid, isbn, isdeleted, isenable, itemstate, itemtype, lastmodificationtime, lastmodifieruserid, locationid, locationname, origintype, pages, precallno, pressmarkid, pressmarkname, price, pubdate, publisher, pubno, remark, summary, tenantid, title
[2025-03-03 13:40:32,514] [basehttp.py:212] [basehttp:log_message] [ERROR]- "GET /api/libitems/search-by-name/?name=Owen HTTP/1.1" 500 144321
[2025-03-03 13:40:46,933] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views_list/libitemviewset.py changed, reloading.
[2025-03-03 13:41:49,130] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 13:42:01,608] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/libitems/search-by-name/
Traceback (most recent call last):
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/owen/.local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/owen/.local/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/owen/.local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/owen/.local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/owen/.local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/owen/.local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/owen/Github/PythonOwen/djangoapi/djapps/api/views_list/libitemviewset.py", line 51, in search_by_name
    results = Libitem.objects.filter(name__icontains=name)
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1546, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1577, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1427, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1237, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1725, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'name' into field. Choices are: author, barcode, bookbarcode, callno, catalogcode, createtype, creationtime, creatoruserid, deleteruserid, deletiontime, id, infoid, isbn, isdeleted, isenable, itemstate, itemtype, lastmodificationtime, lastmodifieruserid, locationid, locationname, origintype, pages, precallno, pressmarkid, pressmarkname, price, pubdate, publisher, pubno, remark, summary, tenantid, title
[2025-03-03 13:42:01,615] [basehttp.py:212] [basehttp:log_message] [ERROR]- "GET /api/libitems/search-by-name/?name=Owen HTTP/1.1" 500 144907
[2025-03-03 13:42:25,095] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/libitems/search-by-name/
Traceback (most recent call last):
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/owen/.local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/owen/.local/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/owen/.local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/owen/.local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/owen/.local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/owen/.local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/owen/Github/PythonOwen/djangoapi/djapps/api/views_list/libitemviewset.py", line 51, in search_by_name
    results = Libitem.objects.filter(name__icontains=name)
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1546, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1577, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1427, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1237, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1725, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'name' into field. Choices are: author, barcode, bookbarcode, callno, catalogcode, createtype, creationtime, creatoruserid, deleteruserid, deletiontime, id, infoid, isbn, isdeleted, isenable, itemstate, itemtype, lastmodificationtime, lastmodifieruserid, locationid, locationname, origintype, pages, precallno, pressmarkid, pressmarkname, price, pubdate, publisher, pubno, remark, summary, tenantid, title
[2025-03-03 13:42:25,098] [basehttp.py:212] [basehttp:log_message] [ERROR]- "GET /api/libitems/search-by-name/?name=Owen HTTP/1.1" 500 144907
[2025-03-03 13:42:30,593] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views_list/libitemviewset.py changed, reloading.
[2025-03-03 13:42:44,728] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 13:42:53,783] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/libitems/search-by-name/
Traceback (most recent call last):
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/owen/.local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/owen/.local/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/owen/.local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/owen/.local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/owen/.local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/owen/.local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/owen/Github/PythonOwen/djangoapi/djapps/api/views_list/libitemviewset.py", line 51, in search_by_name
    results = Libitem.objects.filter(name__icontains=name)
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1546, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1577, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1427, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1237, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1725, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'name' into field. Choices are: author, barcode, bookbarcode, callno, catalogcode, createtype, creationtime, creatoruserid, deleteruserid, deletiontime, id, infoid, isbn, isdeleted, isenable, itemstate, itemtype, lastmodificationtime, lastmodifieruserid, locationid, locationname, origintype, pages, precallno, pressmarkid, pressmarkname, price, pubdate, publisher, pubno, remark, summary, tenantid, title
[2025-03-03 13:42:53,791] [basehttp.py:212] [basehttp:log_message] [ERROR]- "GET /api/libitems/search-by-name/?name=Owen HTTP/1.1" 500 144907
[2025-03-03 13:43:14,907] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/libitems/search-by-name/
Traceback (most recent call last):
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/owen/.local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/owen/.local/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/owen/.local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/owen/.local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/owen/.local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/owen/.local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/owen/Github/PythonOwen/djangoapi/djapps/api/views_list/libitemviewset.py", line 51, in search_by_name
    results = Libitem.objects.filter(name__icontains=name)
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1546, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1577, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1427, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1237, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/home/owen/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1725, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'name' into field. Choices are: author, barcode, bookbarcode, callno, catalogcode, createtype, creationtime, creatoruserid, deleteruserid, deletiontime, id, infoid, isbn, isdeleted, isenable, itemstate, itemtype, lastmodificationtime, lastmodifieruserid, locationid, locationname, origintype, pages, precallno, pressmarkid, pressmarkname, price, pubdate, publisher, pubno, remark, summary, tenantid, title
[2025-03-03 13:43:14,921] [basehttp.py:212] [basehttp:log_message] [ERROR]- "GET /api/libitems/search-by-name/?name=Owen HTTP/1.1" 500 144907
[2025-03-03 13:43:43,690] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views_list/libitemviewset.py changed, reloading.
[2025-03-03 13:43:45,762] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 13:43:56,266] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/libitems/search-by-name/?name=Owen HTTP/1.1" 200 15
[2025-03-03 13:44:03,919] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views_list/libitemviewset.py changed, reloading.
[2025-03-03 13:44:05,918] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 13:52:49,044] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 13:53:29,131] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views_list/libitem_view.py changed, reloading.
[2025-03-03 13:53:33,397] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 13:53:37,879] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/libitem?page=1&size=10 HTTP/1.1" 200 8818
[2025-03-03 13:53:55,493] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/libitems/search-by-name/?name=Owen HTTP/1.1" 200 15
[2025-03-03 13:54:02,030] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/libitems/search-by-name?name=%E8%AD%A6%E6%8E%A2%E9%95%BF%EF%BC%8E2 HTTP/1.1" 301 0
[2025-03-03 13:54:02,185] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/libitems/search-by-name/?name=%E8%AD%A6%E6%8E%A2%E9%95%BF%EF%BC%8E2 HTTP/1.1" 200 2548
[2025-03-03 13:54:56,445] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/libitem?page=1&size=10 HTTP/1.1" 200 8818
[2025-03-03 13:55:11,476] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/libitems/search-by-name?name=%E9%95%BF%E7%9C%A0%E4%B8%8D%E9%86%92 HTTP/1.1" 301 0
[2025-03-03 13:55:11,667] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/libitems/search-by-name/?name=%E9%95%BF%E7%9C%A0%E4%B8%8D%E9%86%92 HTTP/1.1" 200 1813
[2025-03-03 13:57:21,922] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 13:57:26,334] [log.py:241] [log:log_response] [WARNING]- Unauthorized: /api/libitems/
[2025-03-03 13:57:26,337] [basehttp.py:212] [basehttp:log_message] [WARNING]- "GET /api/libitems/?page=1&size=10 HTTP/1.1" 401 4871
[2025-03-03 13:57:43,135] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/libitems?page=1&size=10 HTTP/1.1" 301 0
[2025-03-03 13:57:43,152] [log.py:241] [log:log_response] [WARNING]- Unauthorized: /api/libitems/
[2025-03-03 13:57:43,153] [basehttp.py:212] [basehttp:log_message] [WARNING]- "GET /api/libitems/?page=1&size=10 HTTP/1.1" 401 4871
[2025-03-03 13:59:54,589] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 14:00:24,962] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 14:01:16,880] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views_list/libitem_viewset.py changed, reloading.
[2025-03-03 14:01:18,682] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 14:01:24,941] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views_list/libitem_viewset.py changed, reloading.
[2025-03-03 14:01:44,598] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 14:01:59,314] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views_list/libitem_viewset.py changed, reloading.
[2025-03-03 14:02:02,938] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 14:03:16,512] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 14:03:58,896] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views_list/libitem_viewset.py changed, reloading.
[2025-03-03 14:04:00,814] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 14:04:24,696] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views_list/libitem_viewset.py changed, reloading.
[2025-03-03 14:04:28,020] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 14:04:30,987] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views_list/libitem_viewset.py changed, reloading.
[2025-03-03 14:04:35,930] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 14:04:39,251] [log.py:241] [log:log_response] [WARNING]- Unauthorized: /api/libitems/search-by-name/
[2025-03-03 14:04:39,254] [basehttp.py:212] [basehttp:log_message] [WARNING]- "GET /api/libitems/search-by-name/?name=Owen HTTP/1.1" 401 5014
[2025-03-03 14:04:50,024] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views_list/libitem_viewset.py changed, reloading.
[2025-03-03 14:04:54,015] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 14:04:56,821] [log.py:241] [log:log_response] [WARNING]- Unauthorized: /api/libitems/search-by-name/
[2025-03-03 14:04:56,824] [basehttp.py:212] [basehttp:log_message] [WARNING]- "GET /api/libitems/search-by-name/?name=Owen HTTP/1.1" 401 5014
[2025-03-03 14:06:30,706] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views_list/libitem_viewset.py changed, reloading.
[2025-03-03 14:08:57,735] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 14:09:00,878] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/libitems/?page=1&size=10 HTTP/1.1" 200 8818
[2025-03-03 14:10:37,474] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 14:10:41,003] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/libitems/?page=1&size=10 HTTP/1.1" 200 8818
[2025-03-03 14:11:57,615] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 14:12:04,661] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views_list/libitem_viewset.py changed, reloading.
[2025-03-03 14:12:06,517] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 14:12:26,477] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views_list/libitem_viewset.py changed, reloading.
[2025-03-03 14:12:35,715] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/libitems/search-by-name/?name=Owen HTTP/1.1" 200 15
[2025-03-03 14:12:48,713] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/libitems/search-by-name/?name=Owen HTTP/1.1" 200 15
[2025-03-03 14:12:56,505] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/libitems/search-by-name/?name=%E9%95%BF%E7%9C%A0%E4%B8%8D%E9%86%92 HTTP/1.1" 200 1813
[2025-03-03 14:13:40,493] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 14:13:46,056] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views_list/libitem_viewset.py changed, reloading.
[2025-03-03 14:13:50,987] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 14:14:05,904] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views_list/libitem_viewset.py changed, reloading.
[2025-03-03 14:14:10,550] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 14:14:20,900] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/libitems/search-by-name/
Traceback (most recent call last):
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/owen/.local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/owen/.local/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/owen/.local/lib/python3.10/site-packages/rest_framework/views.py", line 492, in dispatch
    request = self.initialize_request(request, *args, **kwargs)
  File "/home/owen/.local/lib/python3.10/site-packages/rest_framework/viewsets.py", line 146, in initialize_request
    request = super().initialize_request(request, *args, **kwargs)
  File "/home/owen/.local/lib/python3.10/site-packages/rest_framework/views.py", line 394, in initialize_request
    authenticators=self.get_authenticators(),
  File "/home/owen/Github/PythonOwen/djangoapi/djapps/api/views_list/libitem_viewset.py", line 34, in get_authenticators
    if self.action == 'search_by_name':  # 检查是否为 search_by_name 动作
AttributeError: 'LibItemViewSet' object has no attribute 'action'
[2025-03-03 14:14:20,905] [basehttp.py:212] [basehttp:log_message] [ERROR]- "GET /api/libitems/search-by-name/?name=%E9%95%BF%E7%9C%A0%E4%B8%8D%E9%86%92 HTTP/1.1" 500 93682
[2025-03-03 14:15:19,879] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views_list/libitem_viewset.py changed, reloading.
[2025-03-03 14:15:23,883] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 14:15:32,167] [log.py:241] [log:log_response] [WARNING]- Unauthorized: /api/libitems/search-by-name/
[2025-03-03 14:15:32,170] [basehttp.py:212] [basehttp:log_message] [WARNING]- "GET /api/libitems/search-by-name/?name=%E9%95%BF%E7%9C%A0%E4%B8%8D%E9%86%92 HTTP/1.1" 401 5420
[2025-03-03 14:15:46,548] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/libitems/?page=1&size=10 HTTP/1.1" 200 8818
[2025-03-03 14:19:45,851] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 14:19:57,871] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/libitems/search-by-name/?name=%E9%95%BF%E7%9C%A0%E4%B8%8D%E9%86%92 HTTP/1.1" 200 1813
[2025-03-03 14:23:28,749] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 14:23:36,515] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/libitems/search-by-name/?name=Owen HTTP/1.1" 200 15
[2025-03-03 14:23:55,212] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views_list/libitem_viewset.py changed, reloading.
[2025-03-03 14:23:59,230] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 14:24:08,386] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/libitems/search-by-name/?name=%E9%95%BF%E7%9C%A0%E4%B8%8D%E9%86%92 HTTP/1.1" 200 1813
[2025-03-03 14:24:21,684] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views_list/libitem_viewset.py changed, reloading.
[2025-03-03 14:24:56,168] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 14:25:00,000] [log.py:241] [log:log_response] [WARNING]- Unauthorized: /api/libitems/search-by-name/
[2025-03-03 14:25:00,003] [basehttp.py:212] [basehttp:log_message] [WARNING]- "GET /api/libitems/search-by-name/?name=%E9%95%BF%E7%9C%A0%E4%B8%8D%E9%86%92 HTTP/1.1" 401 5420
[2025-03-03 14:25:13,135] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/libitems/?page=1&size=10 HTTP/1.1" 200 8818
[2025-03-03 14:27:27,060] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 14:27:30,118] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/libitems/?page=1&size=10 HTTP/1.1" 200 8818
[2025-03-03 14:31:07,842] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 14:31:34,389] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 14:31:58,397] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/libitems/GetItemList HTTP/1.1" 301 0
[2025-03-03 14:31:58,528] [log.py:241] [log:log_response] [WARNING]- Method Not Allowed: /api/libitems/GetItemList/
[2025-03-03 14:31:58,532] [basehttp.py:212] [basehttp:log_message] [WARNING]- "GET /api/libitems/GetItemList/ HTTP/1.1" 405 6451
[2025-03-03 14:32:14,671] [log.py:241] [log:log_response] [WARNING]- Method Not Allowed: /api/libitems/GetItemList/
[2025-03-03 14:32:14,676] [basehttp.py:212] [basehttp:log_message] [WARNING]- "GET /api/libitems/GetItemList/ HTTP/1.1" 405 6451
[2025-03-03 14:32:23,031] [log.py:241] [log:log_response] [WARNING]- Method Not Allowed: /api/libitems/GetItemList/
[2025-03-03 14:32:23,035] [basehttp.py:212] [basehttp:log_message] [WARNING]- "GET /api/libitems/GetItemList/ HTTP/1.1" 405 6451
[2025-03-03 14:33:04,045] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 14:33:42,595] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 14:34:01,371] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views_list/libitem_viewset.py changed, reloading.
[2025-03-03 14:34:03,464] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 14:34:06,246] [log.py:241] [log:log_response] [WARNING]- Method Not Allowed: /api/libitems/GetItemList/
[2025-03-03 14:34:06,253] [basehttp.py:212] [basehttp:log_message] [WARNING]- "GET /api/libitems/GetItemList/ HTTP/1.1" 405 6451
[2025-03-03 14:34:15,538] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 14:34:18,211] [log.py:241] [log:log_response] [WARNING]- Method Not Allowed: /api/libitems/GetItemList/
[2025-03-03 14:34:18,215] [basehttp.py:212] [basehttp:log_message] [WARNING]- "GET /api/libitems/GetItemList/ HTTP/1.1" 405 6451
[2025-03-03 14:34:18,401] [log.py:241] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2025-03-03 14:34:18,403] [basehttp.py:212] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 2490
[2025-03-03 14:34:28,637] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/libitems/GetItemList/
Traceback (most recent call last):
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/owen/.local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/owen/.local/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/owen/.local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/owen/.local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/owen/.local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/owen/.local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/owen/Github/PythonOwen/djangoapi/djapps/api/views_list/libitem_viewset.py", line 147, in GetItemList
    begintime=datetime.now()
AttributeError: module 'datetime' has no attribute 'now'
[2025-03-03 14:34:28,655] [basehttp.py:212] [basehttp:log_message] [ERROR]- "POST /api/libitems/GetItemList/ HTTP/1.1" 500 98418
[2025-03-03 14:36:00,503] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views_list/libitem_viewset.py changed, reloading.
[2025-03-03 14:36:02,648] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 14:36:05,910] [log.py:241] [log:log_response] [WARNING]- Method Not Allowed: /api/libitems/GetItemList/
[2025-03-03 14:36:05,914] [basehttp.py:212] [basehttp:log_message] [WARNING]- "GET /api/libitems/GetItemList/ HTTP/1.1" 405 6451
[2025-03-03 14:36:13,710] [libitem_viewset.py:148] [libitem_viewset:GetItemList] [INFO]- 进入方法时间:2025-03-03 14:36:12
[2025-03-03 14:36:42,389] [libitem_viewset.py:203] [libitem_viewset:GetItemList] [INFO]- 结束方法时间:2025-03-03 14:36:42
[2025-03-03 14:36:42,412] [basehttp.py:212] [basehttp:log_message] [INFO]- "POST /api/libitems/GetItemList/ HTTP/1.1" 200 88345
[2025-03-03 14:36:42,489] [log.py:241] [log:log_response] [WARNING]- Method Not Allowed: /api/libitems/GetItemList/
[2025-03-03 14:36:42,492] [basehttp.py:212] [basehttp:log_message] [WARNING]- "GET /api/libitems/GetItemList/ HTTP/1.1" 405 6451
[2025-03-03 14:37:20,412] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/libitems/search-by-name/?name=%E9%95%BF%E7%9C%A0%E4%B8%8D%E9%86%92 HTTP/1.1" 200 1813
[2025-03-03 14:37:47,351] [libitem_viewset.py:148] [libitem_viewset:GetItemList] [INFO]- 进入方法时间:2025-03-03 14:37:47
[2025-03-03 14:37:50,045] [libitem_viewset.py:203] [libitem_viewset:GetItemList] [INFO]- 结束方法时间:2025-03-03 14:37:50
[2025-03-03 14:37:50,054] [basehttp.py:212] [basehttp:log_message] [INFO]- "POST /api/libitems/GetItemList/ HTTP/1.1" 200 88345
[2025-03-03 14:37:50,096] [log.py:241] [log:log_response] [WARNING]- Method Not Allowed: /api/libitems/GetItemList/
[2025-03-03 14:37:50,098] [basehttp.py:212] [basehttp:log_message] [WARNING]- "GET /api/libitems/GetItemList/ HTTP/1.1" 405 6451
[2025-03-03 14:38:01,511] [libitem_viewset.py:148] [libitem_viewset:GetItemList] [INFO]- 进入方法时间:2025-03-03 14:38:01
[2025-03-03 14:38:23,393] [libitem_viewset.py:203] [libitem_viewset:GetItemList] [INFO]- 结束方法时间:2025-03-03 14:38:23
[2025-03-03 14:38:35,969] [basehttp.py:212] [basehttp:log_message] [INFO]- "POST /api/libitems/GetItemList/ HTTP/1.1" 200 88345
[2025-03-03 14:38:36,056] [log.py:241] [log:log_response] [WARNING]- Method Not Allowed: /api/libitems/GetItemList/
[2025-03-03 14:38:36,057] [basehttp.py:212] [basehttp:log_message] [WARNING]- "GET /api/libitems/GetItemList/ HTTP/1.1" 405 6451
[2025-03-03 14:40:00,870] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views_list/libitem_viewset.py changed, reloading.
[2025-03-03 14:40:03,258] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 14:40:19,269] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views_list/libitem_viewset.py changed, reloading.
[2025-03-03 14:40:24,139] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 14:41:11,590] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views_list/libitem_viewset.py changed, reloading.
[2025-03-03 14:41:16,215] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 14:41:26,132] [log.py:241] [log:log_response] [WARNING]- Method Not Allowed: /api/libitems/GetItemList/
[2025-03-03 14:41:26,135] [basehttp.py:212] [basehttp:log_message] [WARNING]- "GET /api/libitems/GetItemList/ HTTP/1.1" 405 6451
[2025-03-03 14:41:35,322] [libitem_viewset.py:148] [libitem_viewset:GetItemList] [INFO]- 进入方法时间:2025-03-03 14:41:35
[2025-03-03 14:41:40,172] [libitem_viewset.py:197] [libitem_viewset:GetItemList] [INFO]- 结束方法时间:2025-03-03 14:41:40
[2025-03-03 14:41:40,199] [basehttp.py:212] [basehttp:log_message] [INFO]- "POST /api/libitems/GetItemList/ HTTP/1.1" 200 88345
[2025-03-03 14:41:40,286] [log.py:241] [log:log_response] [WARNING]- Method Not Allowed: /api/libitems/GetItemList/
[2025-03-03 14:41:40,287] [basehttp.py:212] [basehttp:log_message] [WARNING]- "GET /api/libitems/GetItemList/ HTTP/1.1" 405 6451
[2025-03-03 14:43:44,391] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views_list/libitem_viewset.py changed, reloading.
[2025-03-03 14:43:50,131] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 14:44:07,227] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/libitems/ItemList HTTP/1.1" 301 0
[2025-03-03 14:44:07,363] [log.py:241] [log:log_response] [WARNING]- Method Not Allowed: /api/libitems/ItemList/
[2025-03-03 14:44:07,369] [basehttp.py:212] [basehttp:log_message] [WARNING]- "GET /api/libitems/ItemList/ HTTP/1.1" 405 6418
[2025-03-03 14:44:14,728] [libitem_viewset.py:148] [libitem_viewset:ItemList] [INFO]- 进入方法时间:2025-03-03 14:44:14
[2025-03-03 14:44:14,952] [libitem_viewset.py:197] [libitem_viewset:ItemList] [INFO]- 结束方法时间:2025-03-03 14:44:14
[2025-03-03 14:44:14,971] [basehttp.py:212] [basehttp:log_message] [INFO]- "POST /api/libitems/ItemList/ HTTP/1.1" 200 88345
[2025-03-03 14:44:15,011] [log.py:241] [log:log_response] [WARNING]- Method Not Allowed: /api/libitems/ItemList/
[2025-03-03 14:44:15,013] [basehttp.py:212] [basehttp:log_message] [WARNING]- "GET /api/libitems/ItemList/ HTTP/1.1" 405 6418
[2025-03-03 14:44:32,451] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views_list/libitem_viewset.py changed, reloading.
[2025-03-03 14:44:34,405] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 14:44:38,679] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views_list/libitem_viewset.py changed, reloading.
[2025-03-03 14:45:16,821] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 14:45:25,215] [log.py:241] [log:log_response] [WARNING]- Method Not Allowed: /api/libitems/GetItemList/
[2025-03-03 14:45:25,217] [basehttp.py:212] [basehttp:log_message] [WARNING]- "GET /api/libitems/GetItemList/ HTTP/1.1" 405 6451
[2025-03-03 14:46:06,624] [libitem_viewset.py:148] [libitem_viewset:GetItemList] [INFO]- 进入方法时间:2025-03-03 14:46:05
[2025-03-03 14:46:32,844] [libitem_viewset.py:197] [libitem_viewset:GetItemList] [INFO]- 结束方法时间:2025-03-03 14:46:32
[2025-03-03 14:46:35,100] [basehttp.py:212] [basehttp:log_message] [INFO]- "POST /api/libitems/GetItemList/ HTTP/1.1" 200 8782
[2025-03-03 14:46:35,146] [log.py:241] [log:log_response] [WARNING]- Method Not Allowed: /api/libitems/GetItemList/
[2025-03-03 14:46:35,147] [basehttp.py:212] [basehttp:log_message] [WARNING]- "GET /api/libitems/GetItemList/ HTTP/1.1" 405 6451
[2025-03-03 14:46:43,884] [log.py:241] [log:log_response] [WARNING]- Method Not Allowed: /api/libitems/GetItemList/
[2025-03-03 14:46:43,886] [basehttp.py:212] [basehttp:log_message] [WARNING]- "GET /api/libitems/GetItemList/ HTTP/1.1" 405 6451
[2025-03-03 14:47:23,639] [libitem_viewset.py:148] [libitem_viewset:GetItemList] [INFO]- 进入方法时间:2025-03-03 14:47:23
[2025-03-03 14:47:23,839] [libitem_viewset.py:197] [libitem_viewset:GetItemList] [INFO]- 结束方法时间:2025-03-03 14:47:23
[2025-03-03 14:47:23,856] [basehttp.py:212] [basehttp:log_message] [INFO]- "POST /api/libitems/GetItemList/ HTTP/1.1" 200 88345
[2025-03-03 14:52:52,185] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 14:52:56,328] [log.py:241] [log:log_response] [WARNING]- Method Not Allowed: /api/libitems/GetItemList/
[2025-03-03 14:52:56,336] [basehttp.py:212] [basehttp:log_message] [WARNING]- "GET /api/libitems/GetItemList/ HTTP/1.1" 405 9752
[2025-03-03 14:53:06,165] [libitemviewset.py:263] [libitemviewset:GetItemList] [INFO]- 进入方法时间:2025-03-03 14:53:06
[2025-03-03 14:53:06,966] [libitemviewset.py:318] [libitemviewset:GetItemList] [INFO]- 结束方法时间:2025-03-03 14:53:06
[2025-03-03 14:53:06,972] [basehttp.py:212] [basehttp:log_message] [INFO]- "POST /api/libitems/GetItemList/ HTTP/1.1" 200 88345
[2025-03-03 14:54:30,267] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 14:54:40,235] [libitemviewset.py:263] [libitemviewset:GetItemList] [INFO]- 进入方法时间:2025-03-03 14:54:40
[2025-03-03 14:54:40,962] [libitemviewset.py:318] [libitemviewset:GetItemList] [INFO]- 结束方法时间:2025-03-03 14:54:40
[2025-03-03 14:54:40,969] [basehttp.py:212] [basehttp:log_message] [INFO]- "POST /api/libitems/GetItemList/ HTTP/1.1" 200 88345
[2025-03-03 15:05:19,538] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 15:05:25,433] [log.py:241] [log:log_response] [WARNING]- Method Not Allowed: /api/libitems/GetItemList/
[2025-03-03 15:05:25,436] [basehttp.py:212] [basehttp:log_message] [WARNING]- "GET /api/libitems/GetItemList/ HTTP/1.1" 405 9752
[2025-03-03 15:05:28,044] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/libitems HTTP/1.1" 301 0
[2025-03-03 15:05:28,297] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/libitems/
Traceback (most recent call last):
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/owen/.local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/owen/.local/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/owen/.local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/owen/.local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/owen/.local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/owen/.local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/owen/Github/PythonOwen/djangoapi/djapps/api/views_list/libitemviewset.py", line 116, in list
    return JsonResponse(status=405)  # 禁用 GET 列表方法
TypeError: JsonResponse.__init__() missing 1 required positional argument: 'data'
[2025-03-03 15:05:28,301] [basehttp.py:212] [basehttp:log_message] [ERROR]- "GET /api/libitems/ HTTP/1.1" 500 97825
[2025-03-03 15:05:50,841] [log.py:241] [log:log_response] [WARNING]- Method Not Allowed: /api/libitems/GetItemList/
[2025-03-03 15:05:50,843] [basehttp.py:212] [basehttp:log_message] [WARNING]- "GET /api/libitems/GetItemList/ HTTP/1.1" 405 9752
[2025-03-03 15:06:02,569] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/libitems/
Traceback (most recent call last):
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/owen/.local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/owen/.local/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/owen/.local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/owen/.local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/owen/.local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/owen/.local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/owen/Github/PythonOwen/djangoapi/djapps/api/views_list/libitemviewset.py", line 116, in list
    return JsonResponse(status=405)  # 禁用 GET 列表方法
TypeError: JsonResponse.__init__() missing 1 required positional argument: 'data'
[2025-03-03 15:06:02,574] [basehttp.py:212] [basehttp:log_message] [ERROR]- "GET /api/libitems/ HTTP/1.1" 500 98137
[2025-03-03 15:06:13,149] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/libitems/search-bby-name/
Traceback (most recent call last):
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/owen/.local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/owen/.local/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/owen/.local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/owen/.local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/owen/.local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/owen/.local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/owen/Github/PythonOwen/djangoapi/djapps/api/views_list/libitemviewset.py", line 118, in retrieve
    return JsonResponse(status=405)  # 禁用 GET 获取单个资源方法
TypeError: JsonResponse.__init__() missing 1 required positional argument: 'data'
[2025-03-03 15:06:13,151] [basehttp.py:212] [basehttp:log_message] [ERROR]- "GET /api/libitems/search-bby-name/?name=%E9%95%BF%E7%9C%A0%E4%B8%8D%E9%86%92 HTTP/1.1" 500 99573
[2025-03-03 15:06:26,283] [log.py:241] [log:log_response] [WARNING]- Unauthorized: /api/libitem
[2025-03-03 15:06:26,287] [basehttp.py:212] [basehttp:log_message] [WARNING]- "GET /api/libitem?page=1&size=10 HTTP/1.1" 401 4832
[2025-03-03 15:06:28,989] [log.py:241] [log:log_response] [WARNING]- Unauthorized: /api/libitem
[2025-03-03 15:06:28,990] [basehttp.py:212] [basehttp:log_message] [WARNING]- "GET /api/libitem?page=1&size=10 HTTP/1.1" 401 4832
[2025-03-03 15:06:31,109] [log.py:241] [log:log_response] [WARNING]- Unauthorized: /api/libitem
[2025-03-03 15:06:31,111] [basehttp.py:212] [basehttp:log_message] [WARNING]- "GET /api/libitem?page=1&size=10 HTTP/1.1" 401 4832
[2025-03-03 15:06:34,494] [log.py:241] [log:log_response] [WARNING]- Unauthorized: /api/libitem
[2025-03-03 15:06:34,502] [basehttp.py:212] [basehttp:log_message] [WARNING]- "GET /api/libitem HTTP/1.1" 401 4771
[2025-03-03 15:06:37,716] [log.py:241] [log:log_response] [WARNING]- Unauthorized: /api/libitem
[2025-03-03 15:06:37,717] [basehttp.py:212] [basehttp:log_message] [WARNING]- "GET /api/libitem HTTP/1.1" 401 4771
[2025-03-03 15:06:45,213] [log.py:241] [log:log_response] [WARNING]- Unauthorized: /api/libitem
[2025-03-03 15:06:45,214] [basehttp.py:212] [basehttp:log_message] [WARNING]- "GET /api/libitem?name=Owen HTTP/1.1" 401 4805
[2025-03-03 15:06:57,084] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/hello?name=Owen HTTP/1.1" 200 28
[2025-03-03 15:07:06,608] [log.py:241] [log:log_response] [WARNING]- Unauthorized: /api/libitem
[2025-03-03 15:07:06,614] [basehttp.py:212] [basehttp:log_message] [WARNING]- "GET /api/libitem?page=1&size=10 HTTP/1.1" 401 4832
[2025-03-03 15:07:32,208] [log.py:241] [log:log_response] [WARNING]- Unauthorized: /api/libitem
[2025-03-03 15:07:32,211] [basehttp.py:212] [basehttp:log_message] [WARNING]- "POST /api/libitem?page=1&size=10 HTTP/1.1" 401 4833
[2025-03-03 15:08:36,823] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 15:08:43,211] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/libitem?page=1&size=10 HTTP/1.1" 200 8818
[2025-03-03 15:40:10,690] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 15:40:17,813] [log.py:241] [log:log_response] [WARNING]- Method Not Allowed: /api/libitems/GetItemList/
[2025-03-03 15:40:17,819] [basehttp.py:212] [basehttp:log_message] [WARNING]- "GET /api/libitems/GetItemList/ HTTP/1.1" 405 9752
[2025-03-03 15:40:21,262] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/libitem?page=1&size=10 HTTP/1.1" 200 8818
[2025-03-03 15:46:35,512] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 15:50:06,704] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 15:50:12,152] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/libitem?page=1&size=10 HTTP/1.1" 200 8818
[2025-03-03 15:50:12,260] [log.py:241] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2025-03-03 15:50:12,262] [basehttp.py:212] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 2490
