[2025-03-03 09:01:24,479] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 09:01:42,903] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/hello/
Traceback (most recent call last):
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py", line 15, in hello
    print("GET:"+params)
TypeError: can only concatenate str (not "dict") to str
[2025-03-03 09:01:42,916] [basehttp.py:212] [basehttp:log_message] [ERROR]- "GET /api/hello/ HTTP/1.1" 500 68732
[2025-03-03 09:01:54,227] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/hello/
Traceback (most recent call last):
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py", line 15, in hello
    print("GET:"+params)
TypeError: can only concatenate str (not "dict") to str
[2025-03-03 09:01:54,237] [basehttp.py:212] [basehttp:log_message] [ERROR]- "GET /api/hello/ HTTP/1.1" 500 68732
[2025-03-03 09:02:06,101] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py changed, reloading.
[2025-03-03 09:02:10,033] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 09:02:29,583] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 09:02:34,052] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/hello?abc=1 HTTP/1.1" 301 0
[2025-03-03 09:02:44,714] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/hello/
Traceback (most recent call last):
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py", line 15, in hello
    print("GET:"+params)
TypeError: can only concatenate str (not "dict") to str
[2025-03-03 09:02:44,729] [basehttp.py:212] [basehttp:log_message] [ERROR]- "GET /api/hello/?abc=1 HTTP/1.1" 500 71701
[2025-03-03 09:02:44,947] [log.py:241] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2025-03-03 09:02:44,949] [basehttp.py:212] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 2214
[2025-03-03 09:03:16,182] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py changed, reloading.
[2025-03-03 09:03:18,396] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 09:03:27,745] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/hello?abc=1 HTTP/1.1" 301 0
[2025-03-03 09:03:43,753] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 09:03:51,958] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/hello?abc=1 HTTP/1.1" 301 0
[2025-03-03 09:03:59,111] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/hello?abc=1 HTTP/1.1" 301 0
[2025-03-03 09:04:15,103] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py changed, reloading.
[2025-03-03 09:04:17,003] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 09:04:37,803] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 09:04:45,273] [log.py:241] [log:log_response] [WARNING]- Not Found: /api/hello/abc=1
[2025-03-03 09:04:45,276] [basehttp.py:212] [basehttp:log_message] [WARNING]- "GET /api/hello/abc=1 HTTP/1.1" 404 2281
[2025-03-03 09:05:00,215] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py changed, reloading.
[2025-03-03 09:05:08,907] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 09:05:19,120] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/hello?abc=1 HTTP/1.1" 301 0
[2025-03-03 09:05:22,247] [log.py:241] [log:log_response] [WARNING]- Not Found: /api/hello/abc=1
[2025-03-03 09:05:22,249] [basehttp.py:212] [basehttp:log_message] [WARNING]- "GET /api/hello/abc=1 HTTP/1.1" 404 2281
[2025-03-03 09:06:42,390] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py changed, reloading.
[2025-03-03 09:06:44,458] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 09:07:25,281] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 09:07:34,329] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/hello/
Traceback (most recent call last):
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py", line 11, in hello
    print("user_agent:"+json.dumps(params))
UnboundLocalError: local variable 'params' referenced before assignment
[2025-03-03 09:07:34,343] [basehttp.py:212] [basehttp:log_message] [ERROR]- "GET /api/hello/?name=Owen HTTP/1.1" 500 71543
[2025-03-03 09:07:53,497] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py changed, reloading.
[2025-03-03 09:07:55,804] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 09:08:12,684] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/hello/
Traceback (most recent call last):
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py", line 16, in hello
    print("GET:"+params)
TypeError: can only concatenate str (not "dict") to str
[2025-03-03 09:08:12,709] [basehttp.py:212] [basehttp:log_message] [ERROR]- "GET /api/hello/?name=Owen HTTP/1.1" 500 71882
[2025-03-03 09:09:10,976] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 09:09:28,542] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/hello/?name=Owen HTTP/1.1" 200 28
[2025-03-03 09:09:49,222] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py changed, reloading.
[2025-03-03 09:09:51,154] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 09:10:01,911] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py changed, reloading.
[2025-03-03 09:10:12,708] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 09:10:38,765] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/hello/?name=Owen HTTP/1.1" 200 28
[2025-03-03 09:10:50,279] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py changed, reloading.
[2025-03-03 09:10:52,267] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 09:11:51,164] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/urls.py changed, reloading.
[2025-03-03 09:11:55,086] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 09:12:11,980] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/urls.py changed, reloading.
[2025-03-03 09:43:23,298] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 09:43:52,320] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/hello HTTP/1.1" 200 14
[2025-03-03 09:44:01,946] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/hello?name=Owen HTTP/1.1" 200 28
[2025-03-03 09:58:26,267] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 10:51:55,033] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 10:54:30,580] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 10:57:29,874] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 10:59:55,357] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 11:01:36,938] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 11:01:53,470] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/hello?name=Owen HTTP/1.1" 200 28
[2025-03-03 11:01:53,605] [log.py:241] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2025-03-03 11:01:53,608] [basehttp.py:212] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 2214
[2025-03-03 11:02:09,464] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py changed, reloading.
[2025-03-03 11:07:12,919] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 11:07:29,722] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py changed, reloading.
[2025-03-03 11:07:39,928] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 11:08:00,028] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/libitem
Traceback (most recent call last):
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py", line 59, in libitem
    return JsonResponse(datas)
  File "/home/owen/.local/lib/python3.10/site-packages/django/http/response.py", line 724, in __init__
    raise TypeError(
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
[2025-03-03 11:08:00,041] [basehttp.py:212] [basehttp:log_message] [ERROR]- "GET /api/libitem?name=Owen HTTP/1.1" 500 91508
[2025-03-03 11:08:48,531] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py changed, reloading.
[2025-03-03 11:08:50,533] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 11:08:52,071] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py changed, reloading.
[2025-03-03 11:09:02,354] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 11:09:09,379] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/libitem
Traceback (most recent call last):
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py", line 68, in libitem
    return JsonResponse(response_data)
  File "/home/owen/.local/lib/python3.10/site-packages/django/http/response.py", line 731, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/usr/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/serializers/json.py", line 106, in default
    return super().default(o)
  File "/usr/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
[2025-03-03 11:09:09,383] [basehttp.py:212] [basehttp:log_message] [ERROR]- "GET /api/libitem?name=Owen HTTP/1.1" 500 140064
[2025-03-03 11:09:26,553] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/libitem
Traceback (most recent call last):
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py", line 68, in libitem
    return JsonResponse(response_data)
  File "/home/owen/.local/lib/python3.10/site-packages/django/http/response.py", line 731, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/usr/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/serializers/json.py", line 106, in default
    return super().default(o)
  File "/usr/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
[2025-03-03 11:09:26,561] [basehttp.py:212] [basehttp:log_message] [ERROR]- "GET /api/libitem?name=Owen HTTP/1.1" 500 140201
[2025-03-03 11:10:42,848] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py changed, reloading.
[2025-03-03 11:10:45,420] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 11:12:47,042] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/libitem
Traceback (most recent call last):
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py", line 67, in libitem
    return JsonResponse(response_data)
  File "/home/owen/.local/lib/python3.10/site-packages/django/http/response.py", line 731, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/usr/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/serializers/json.py", line 106, in default
    return super().default(o)
  File "/usr/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
[2025-03-03 11:12:47,049] [basehttp.py:212] [basehttp:log_message] [ERROR]- "GET /api/libitem?name=Owen HTTP/1.1" 500 140355
[2025-03-03 11:13:33,694] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/libitem
Traceback (most recent call last):
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py", line 67, in libitem
    return JsonResponse(response_data)
  File "/home/owen/.local/lib/python3.10/site-packages/django/http/response.py", line 731, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/usr/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/serializers/json.py", line 106, in default
    return super().default(o)
  File "/usr/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
[2025-03-03 11:13:33,696] [basehttp.py:212] [basehttp:log_message] [ERROR]- "GET /api/libitem?name=Owen HTTP/1.1" 500 140306
[2025-03-03 11:13:38,027] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/libitem
Traceback (most recent call last):
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py", line 67, in libitem
    return JsonResponse(response_data)
  File "/home/owen/.local/lib/python3.10/site-packages/django/http/response.py", line 731, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/usr/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/serializers/json.py", line 106, in default
    return super().default(o)
  File "/usr/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
[2025-03-03 11:13:38,029] [basehttp.py:212] [basehttp:log_message] [ERROR]- "GET /api/libitem?name=Owen HTTP/1.1" 500 140064
[2025-03-03 11:13:53,276] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 11:14:06,614] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/libitem
Traceback (most recent call last):
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py", line 67, in libitem
    return JsonResponse(response_data)
  File "/home/owen/.local/lib/python3.10/site-packages/django/http/response.py", line 731, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/usr/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/serializers/json.py", line 106, in default
    return super().default(o)
  File "/usr/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
[2025-03-03 11:14:06,617] [basehttp.py:212] [basehttp:log_message] [ERROR]- "GET /api/libitem?name=Owen HTTP/1.1" 500 140064
[2025-03-03 11:14:56,654] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py changed, reloading.
[2025-03-03 11:14:58,572] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 11:15:06,234] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py changed, reloading.
[2025-03-03 11:15:10,139] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 11:15:33,265] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py changed, reloading.
[2025-03-03 11:15:43,243] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 11:15:58,335] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/libitem?name=Owen HTTP/1.1" 200 8848
[2025-03-03 11:18:33,200] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 11:18:42,556] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/libitem?name=Owen HTTP/1.1" 200 8848
[2025-03-03 11:18:50,222] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py changed, reloading.
[2025-03-03 11:18:52,039] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 11:18:55,671] [log.py:241] [log:log_response] [WARNING]- Not Found: /api/libitem
[2025-03-03 11:18:55,674] [basehttp.py:212] [basehttp:log_message] [WARNING]- "GET /api/libitem?name=Owen HTTP/1.1" 404 8848
[2025-03-03 11:21:10,011] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 11:21:18,960] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/libitem?name=Owen HTTP/1.1" 200 8848
[2025-03-03 11:23:44,587] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 11:23:51,042] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/libitem?name=Owen HTTP/1.1" 200 8848
[2025-03-03 11:24:16,425] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 11:24:47,069] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/libitem?name=Owen HTTP/1.1" 200 8848
[2025-03-03 11:24:47,269] [log.py:241] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2025-03-03 11:24:47,271] [basehttp.py:212] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 2214
[2025-03-03 11:24:54,440] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py changed, reloading.
[2025-03-03 11:24:56,604] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 11:25:18,738] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py changed, reloading.
[2025-03-03 11:25:22,626] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 11:26:46,212] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py changed, reloading.
[2025-03-03 11:26:49,801] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 11:27:11,862] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py changed, reloading.
[2025-03-03 11:27:16,363] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 11:27:33,113] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py changed, reloading.
[2025-03-03 11:27:35,047] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 11:27:39,046] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/libitem
Traceback (most recent call last):
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py", line 89, in libitem
    data=convert_model_to_dict(item)
  File "/home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py", line 45, in convert_model_to_dict
    isdeleted_value = value.isdeleted
AttributeError: 'bytes' object has no attribute 'isdeleted'
[2025-03-03 11:27:39,049] [basehttp.py:212] [basehttp:log_message] [ERROR]- "GET /api/libitem?name=Owen HTTP/1.1" 500 78708
[2025-03-03 11:27:56,916] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/libitem
Traceback (most recent call last):
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py", line 89, in libitem
    data=convert_model_to_dict(item)
  File "/home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py", line 45, in convert_model_to_dict
    isdeleted_value = value.isdeleted
AttributeError: 'bytes' object has no attribute 'isdeleted'
[2025-03-03 11:27:56,932] [basehttp.py:212] [basehttp:log_message] [ERROR]- "GET /api/libitem?name=Owen HTTP/1.1" 500 79055
[2025-03-03 11:28:15,666] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py changed, reloading.
[2025-03-03 11:28:17,561] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 11:28:45,616] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/libitem
Traceback (most recent call last):
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/owen/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py", line 84, in libitem
    data=convert_model_to_dict(item)
  File "/home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py", line 40, in convert_model_to_dict
    isdeleted_value = value.isdeleted
AttributeError: 'bytes' object has no attribute 'isdeleted'
[2025-03-03 11:28:45,632] [basehttp.py:212] [basehttp:log_message] [ERROR]- "GET /api/libitem?name=Owen HTTP/1.1" 500 78487
[2025-03-03 11:29:23,209] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py changed, reloading.
[2025-03-03 11:29:25,413] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 11:29:29,036] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py changed, reloading.
[2025-03-03 11:29:33,131] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 11:29:34,640] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py changed, reloading.
[2025-03-03 11:29:38,772] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 11:29:56,339] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/libitem?name=Owen HTTP/1.1" 200 8818
[2025-03-03 11:31:41,380] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/owen/Github/PythonOwen/djangoapi/djapps/api/views.py changed, reloading.
[2025-03-03 11:31:45,061] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 11:32:32,288] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 11:32:43,299] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/libitem?name=Owen HTTP/1.1" 200 8818
[2025-03-03 11:36:29,159] [autoreload.py:668] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2025-03-03 11:36:38,951] [basehttp.py:212] [basehttp:log_message] [INFO]- "GET /api/libitem?name=Owen HTTP/1.1" 200 8818
